const mongoose = require("mongoose")

const transactionSchema = new mongoose.Schema({
    fromAccount:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"account",
        required : [true,"transaction must be associated with a from account"],
        index:true
    },
    toAccount:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"account",
        required:[true,"transaction must be associated with a to account"],
        index:true
    },
    status:{
        type:"string",
        enum:{
            values : ["PENDING","COMPLETED","FAILED"],
            message : "status can be either PENDING,COMPLETED,FAILED"
        },
        default:"PENDING"
    },
    amount:{
        type:Number,
        required:[true,"amount is required for creating a transaction"],
        min:[0,"transaction cannot be negative"]
    },
    idempotencyKey:{
        //prevent the same transaction from rehappen
        //generated by client side
        type:String,
        required:[true,"idempotencyKey is required for creating a transaction"],
        index:true,
        unique:true
    }
},{
    timestamps : true
})

const transactionModel = mongoose.model("transaction",transactionSchema)

module.exports = transactionModel
